[project]
name = "dg"
version = "0.1.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pyright]
# This tells Pyright/Pylance to not report this specific type of issue.
reportUnknownVariableType = "none" 