[backend]
precision = "double"

[solver]
system = "linear-advection"
constants = { c = 1.0 }
order = 3

[solver.time-integration]
scheme = "rk4"
t-start = 0.0
t-end = 5.0
dt = 0.00001

[solver.boundary-conditions]
inlet = { type = "dirichlet", u = 1.0 }
outlet = { type = "extrapolated" }

[solver.interfaces]
riemann-solver = { type = "hllc", beta = 0.9, tau = 1.0 }

[solver.elements.line]
solution-points = "gauss-legendre-lobatto"